# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference

default-environment: &default-environment
  docker:
    - image: cimg/node:18.17.0

step-restore-build-cache: &step-restore-build-cache
  restore_cache:
    name: Restore Yarn Package Cache
    keys:
      - yarn-packages-{{ checksum "yarn.lock" }}

step-save-build-cache: &step-save-build-cache
  save_cache:
    name: Save Yarn Package Cache
    key: yarn-packages-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn

version: 2.1
jobs:
  build:
    <<: *default-environment
    steps:
      - checkout
      - run: node --version
      - <<: *step-restore-build-cache
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - <<: *step-save-build-cache
  lint:
    <<: *default-environment
    steps:
      - checkout
      - <<: *step-restore-build-cache
      - run:
          name: Lint
          command: yarn hardhat check
  test:
    <<: *default-environment
    steps:
      - checkout
      - <<: *step-restore-build-cache
      - run:
          name: Unit tests & coverage
          command: yarn hardhat coverage

workflows:
  version: 2
  build-and-lint:
    jobs:
      - build
      - lint
      - test
  build-lint-test-and-coverage:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
